monolog:
  channels:
    - security_audit
  handlers:
    main:
      type: stream
      path: php://stderr
      level: info
    security_audit:
      type: stream
      path: php://stderr
      level: info
      channels: [security_audit]
