nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['X-Correlation-Id']
    max_age: 3600
  paths:
    '^/api/': null
